spring:
  application:
    name: dispatch-service
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  h2:
    console:
      enabled: true
server:
  port: 9005

management:
  endpoints:
    web:
      exposure:
        include: '*'