spring:
  application:
    name: production-service
  # Spring Datasource configuration
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  # JPA/Hibernate
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
  # h2 console
  h2:
    console:
      enabled: true
#Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9013
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: '*'